config/routes.rb
EdshawMe::Application.routes.draw do

  root 'static_pages#home', as: "home"

  get 'cv/' => 'static_pages#cv', as: "cv"

  get 'blog/' => 'blog#home', as: "blog"

  get 'blog/post/_id:id' => 'blog#getById', as: "blog_id", constraints: {
      id: /\d+/
  }
  get 'blog/post/:slug' => 'blog#getBySlug', as: "blog_slug", constraints: {
  }

    get 'blog/new' => 'blog#new', as: "blog_new"
    post 'blog/new' => 'blog#create', as: "blog_create"

  

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  def self.latest
    return self.order("created_at").last
  end

  def self.latest_n(limit)
    return self.order("created_at DESC").first(limit)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def home
    @latestposts = BlogPost.latest_n(5)
  end

  def getById
    id = params[:id]
    @blog = BlogPost.find(id)
    render "blog/get"
  end

  def getBySlug
    slug = params[:slug]
    @blog = BlogPost.find_by_slug(slug)
    render "blog/get"
  end

  require 'bcrypt'
  include BCrypt
  before_filter :authenticate, only: [:new, :create, :edit]

  # Password on 31st October => "$2a$13$Im8ghHAnErY3aMvvXqqDqOLZDh72EM6aKZ2GcoA6LAnpz4/.uirSy"

  def authenticate
    authenticate_or_request_with_http_basic('Administration') do |username, password|
      hash = Password.new("$2a$13$Im8ghHAnErY3aMvvXqqDqOLZDh72EM6aKZ2GcoA6LAnpz4/.uirSy") # Hash of password to make new Password.
      isAdmin = 'edshaw' == username
      hasPass = hash == password #Password object equality will test if password is original secret.
      isAdmin && hasPass
    end
  end

  def new
    @blogpost = BlogPost.new
  end

  def slugify(title)
    return title
  end

  def create

    puts params

    post = BlogPost.new
    content = params["blog_post"]
    post.title = content["title"]
    post.post = content["post"]
    post.slug = slugify(params[:title])

    post.save

    redirect_to blog_create_path(@post)

  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @latestblogpost = BlogPost.latest
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  @@markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                       :fenced_code_blocks => true,
                                       :disableindented_code_blocks => true,
                                       :superscript => true,
                                       :strikethrough => true,
                                       :highlight => true,
                                       :underline => true,
                                       :footnotes => true,
  )

  def markdown(text)
    return @@markdown.render(text).html_safe
  end

end

app/helpers/blog/blog_helper.rb
module Blog::BlogHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blog/get.html.erb
<%= render partial: "shared/blogpost", locals:{blog: @blog}%>
<hr>
<div class="comments">
  <div id="disqus_thread"></div>
  <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = 'edshaw-me'; // required: replace example with your forum shortname
      var disqus_identifier = "blog:" + <%= @blog.id %> ;

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>

app/views/blog/home.html.erb
<% content_for :title do %>Blog<% end %>

<% if @latestposts.each do |post| %>
<%= render partial: "shared/blogpost", locals:{blog: post, size: "sm"} %>
<% end.empty? %>
<h1>Ed Shaw's Blog</h1>
<p><strong>Sorry, there's nothing here yet!</strong> Come back soon. :)</p>
<% end %>

app/views/blog/new.erb
<%= form_for @blogpost, url: {action: "create"}, html: {class: "blogpost_form"} do |f| %>
    <ul class="form-elems">
        <li><h4>Title</h4><%= f.text_field :title, size: 60 %></li>
        <li><h4>Post</h4><%= f.text_area :post, size: "80x20" %></li>
        <li><%= f.submit "Create" %></li>
    </ul>
<% end %>

app/views/index/get.html.erb
<% content_for :title do %>About Me<% end %>

<h1>Under Construction</h1>
<p>Please come back soon. :)</p>

<h1>About</h1>
<p>I am currently studying for a Masters in Computer Science at Oxford University.</p>

<h1> Education and Experience </h1>
<p> Masters in Computer Science - Oxford University 2010 - 2014</p>
<p> Software Development Engineer in Test - Amazon Development Centre London - Summer 2013</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Ed Shaw<% if content_for?(:title) %> | <%= yield :title %><% end %></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">

  <%= stylesheet_link_tag "bootstrap.min.css" %>
  <style>
      body {
          padding-top: 50px;
          padding-bottom: 20px;
      }
  </style>
  <!--<link rel="stylesheet" href="css/bootstrap-theme.min.css">-->
  <!--<link rel="stylesheet" href="css/main.css">-->
  <%= stylesheet_link_tag "bootstrap-theme.min.css", "application" %>

  <!--<script src="js/vendor/modernizr-2.6.2.min.js">-->
  <%= javascript_include_tag "modernizr-2.6.2.min.js" %>



</head>
<body>
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

<header class="jumbotron">
    <div class="container">
        <h3> Ed Shaw </h3>
        <h2> Home </h2>
    </div>
</header>

<div>
    <%= render 'shared/mainmenu' %>
</div>


<div class="container">
    <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-3 col-sm-push-9" id="sidebar" role="navigation">
            <div class="nav-side">
                <%= render 'shared/navside' %>
            </div>
        </div>

        <div class="col-xs-12 col-sm-9 col-sm-pull-3">
            <div class="content">
                <%= yield %>
            </div>
        </div>
    </div>
</div>

<hr>

<footer class="container">
  <p>edshaw.me - &copy; Ed Shaw - 2013 </p>
  <p>Built with Heroku, Rails, Bootstrap by Twitter, jQuery and Modernizr. Comments provided by Disqus. </p>
  <p>This site uses Google Analytics to learn more about how people view this site.</p>
</footer>
</div> <!-- /container -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<%=j javascript_include_tag "jquery-1.10.1.min.js" %>')</script>

<!--<script src="js/vendor/bootstrap.min.js"></script>-->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-44915129-1', 'edshaw.me');
    ga('send', 'pageview');
</script>
<%= javascript_include_tag "bootstrap.min.js", "application" %>
</body>

app/views/shared/_blogpost.erb
<article class="blogpost panel panel-default">
    <header class="bloghead panel-heading">
        <h2 class="blogtitle panel-title"><%= if (blog.title) then blog.title else "No Title" end%></h2>
        <span class="blogdate"><%= link_to (h(blog.created_at.to_formatted_s(:short)) +raw(" <span class='glyphicon glyphicon-link'></span>")), blog_id_url(id: blog.id) %></span>
    </header>
    <div class ="blogcontent panel-body">
        <p>
          <%= markdown(if (blog.post) then blog.post else "####No Content :(" end)%>
        </p>
        <footer class = "blogauthor">
            <p>~ Ed Shaw</p>
        </footer>
    </div>
</article>

app/views/shared/_mainmenu.erb
<nav id="topnav" class="navbar navbar-default" role="navigation">
  <div class="container">
    <div>
      <ul class="nav navbar-nav">
        <li>
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->

    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "About Me", home_path() %></li>
        <li><%= link_to "Blog", blog_path() %></li>
        <!--<li><a>Contact</a></li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/shared/_navside.erb
<div class="well sidebar-nav">
  <ul class="nav">
    <li><strong>More Me</strong></li>
    <li><a href="https://github.com/EdShaw/"><i class="fa fa-fw fa-github"></i> GitHub</a></li>
    <li><a href="http://www.linkedin.com/profile/view?id=267596592"><i class="fa fa-fw fa-linkedin"></i> LinkedIn</a></li>
    <li><a href="http://careers.stackoverflow.com/edshaw"><i class="fa fa-fw fa-stack-overflow"></i> Careers 2.0</a></li>
    <hr class="nav-hr">
    <!--<li><a href="https://docs.google.com/file/d/0B2SYQosqxGHoWi1rdUM4NGR3MVE"><i class="fa fa-fw fa-file-text-o"></i> My Résumé</a></li>-->
    <li><a href="mailto:edwardshaw9+blog@gmail.com"><i class="fa fa-fw fa-envelope-o"></i> Email Me</a></li>
  </ul>
</div><!--/.well -->

app/views/static_pages/home.html.erb
<% content_for :title do %>About Me<% end %>

<h1>About</h1>
<p>I am currently studying for a Masters in Computer Science at Oxford University. I love learning new technologies, puzzles and gadgets.</p>

<% if @latestblogpost %>
<h1>Latest Blog Post</h1>
<%= render partial: "shared/blogpost", locals:{blog: @latestblogpost, size: "sm"} %>
<% end %>

<h1> Education and Experience </h1>
<p> Masters in Computer Science - Oxford University 2010 - 2014</p>
<p> Software Development Engineer in Test - Amazon Development Centre London - Summer 2013</p>